// Generated by CoffeeScript 1.6.2
var NeDBStore;

NeDBStore = (function() {
  function NeDBStore(db) {
    this.db = db;
    if (typeof this.db !== 'Object') {
      throw new Error('Must be provided an NeDB datastore');
    }
  }

  NeDBStore.prototype.add = function(type, data, cb) {
    data.type = type;
    return this.db.insert(data, cb);
  };

  NeDBStore.prototype.drop = function(type, data, cb) {
    return this.db.remove(data, {}, cb);
  };

  NeDBStore.prototype.get = function(type, data, cb) {
    data.type = type;
    return this.db.findOne(data, cb);
  };

  return NeDBStore;

})();

modules.exports = NeDBStore;
