// Generated by CoffeeScript 1.6.2
var Application, bc, clientIdBytes, clientSecretBytes, crypto, utils;

bc = require('base-converter');

crypto = require('crypto');

utils = require('./utils');

clientIdBytes = 48;

clientSecretBytes = 60;

Application = (function() {
  function Application(server, options) {
    this.server = server;
    this.appId = options.appId, this.appSecret = options.appSecret, this.name = options.name, this.description = options.description, this.owner = options.owner, this.scope = options.scope;
    this.redirectURI = 'urn:ietf:wg:oauth:2.0:oob';
  }

  Application.prototype.create = function(fn) {
    return this.storage.add('application', {
      appId: this.appId,
      appSecret: this.appSecret,
      desc: this.description,
      ownerId: this.owner,
      scope: this.scope
    }, fn);
  };

  Application.prototype.drop = function(fn) {
    return this.storage.drop('application', {
      appId: this.appId
    }, fn);
  };

  Application.makeClientId = function(fn) {
    return utils.randString(clientIdBytes, fn);
  };

  Application.makeClientSecret = function(fn) {
    return utils.randString(clientSecretBytes, fn);
  };

  return Application;

})();

module.exports = Application;
