// Generated by CoffeeScript 1.6.2
/*
ex =
	authCode: {
		appId: ''
		userId: ''
		code: ''
		expiry: ''
	}
	token: {
		appId: ''
		userId: ''
		refreshToken: ''
		accessToken: ''
		expiry: ''
		scope: ''
	}
	application: {
		appId: ''
		appSecret: ''
		ownerId: ''
		name: ''
		desc: ''
		scope: ''
	}
*/

var oauth2;

module.exports = oauth2 = {
  server: require('./server'),
  application: require('./application'),
  utils: require('./utils')
};
