// Generated by CoffeeScript 1.6.2
var utils;

utils = {
  randString: function(size, fn) {
    return crypto.randomBytes(size, function(err, bytes) {
      if (err) {
        return fn(err);
      }
      return fn(null, bc.decTo36(bc.hexToDec(bytes.toString('hex'))));
    });
  }
};

module.exports = utils;
